name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        ref: main
    
    - name: Build
      run: cd website && npm install && npm run build:all
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.BUILD_DEPLOY_ACTION }}
          BRANCH: gh-pages
          FOLDER: website/build